### ISSUE TITLE
[question] read problem

### ISSUE THREAD

**Issue by aeosynth** [huseyinkozan/phonegap-bluetooth#2]
Can the `read` method record audio from bluetooth headsets? The example app gives me an error message when I click the `read` button, so I'm not sure what it actually does.

error message:

```
D/BluetoothPlugin(10299): Action: read
E/BluetoothPlugin(10299): java.lang.ArrayIndexOutOfBoundsException: length=0; index=-1 / length=0; index=-1
```

**Comment by huseyinkozan** [comment]
Actually I could not read data from my BT keyboard. I thought it was BT configuration problem. I may look at that soon, when I find enough free time.

**Comment by huseyinkozan** [comment]
I made some changes but not tested yet. I recommend to test codes with two phone.

**Comment by aeosynth** [comment]
```
D/BluetoothPlugin( 1867): Action: read
D/CordovaLog( 1867): Uncaught Error: Error calling method on NPObject.
D/CordovaLog( 1867): file:///android_asset/www/cordova-2.2.0.js: Line 984 : Uncaught Error: Error calling method on NPObject.
E/Web Console( 1867): Uncaught Error: Error calling method on NPObject. at file:///android_asset/www/cordova-2.2.0.js:984
D/Cordova ( 1867): onPageFinished(file:///android_asset/www/index.html#)
D/DroidGap( 1867): onMessage(onNativeReady,null)
D/DroidGap( 1867): onMessage(onPageFinished,file:///android_asset/www/index.html#)
```

**Comment by aeosynth** [comment]
If I want to send audio from a bluetooth headset, should I call `listen` or `read` or both?

**Comment by romerol** [comment]
Hi guys, I would like to use this plugin. How is the read function working? I just need to read from a bluetooth device. Were you able to solve the issue? Is the function finished? Thanks!

**Comment by huseyinkozan** [comment]
I updated the example to use read() and write. read() and write() needs test and debug if needed. I can not continue development, cause my phone has broken down.

**Comment by romerol** [comment]
Thank you! I deployed the app. The idea would be to start listening in a device and then use the connect button from another device, right? That's why the UUID is hardcoded, am I right? I don't have two devices so I couldn't test this yet.

**Comment by huseyinkozan** [comment]
I am not the Bluetooth gru, but I thing it is working like that. First listen for a UUID, than use another device to connect that UUID. If your device's SDK is grater than 15, you may list the UUIDs, and connect that. Else, use hard coded for it too. You will need two different devices. And maybe two IDEs with debug, dont know.

**Comment by superdikery** [comment]
Hello Hüseyin,

Firstly thanks for putting the work into this! I have been testing the read functionality and believe there may be a couple bugs in the Java code, after fixing these things everything is working very well:

1) line 415: I believe ReadThread.start() is never called.

2) line 717: In the ReadThread, after data is called the run() function calls callback_read.success(). However this seems to close the CallbackContext for future calls, so the Javascript side can only receive one callback. Replacing callback_read.success() with the following allows multiple calls to the callback as more data arrives:

PluginResult result = new PluginResult(PluginResult.Status.OK, next);
result.setKeepCallback(true);
callback_read.sendPluginResult(result);

3) line 708: This is more of an optimization, but I wrapped the OutputStream for writing and InputStream for reading with BufferedWriter and BufferedReader respectively. This allows you to use BufferedReader.readLine() in the ReadThread.run() function, which will block until data is available on the socket.

Thanks again for your time working on this!

**Comment by huseyinkozan** [comment]
Hello Ainsley,
Thank you very much for your interest and help.
1) I added start().
2) Fixed.
3) I added BufferedReader and test it. I finished my free time for BufferedWriter, and didnt add it. I prefered read() rather than readLine(), because someone may want to get binary data.

Can anybody confirm the read() fix ? Than I can close the issue.

Hope it helps someone.
