### ISSUE TITLE
[question] Write Problem

### ISSUE THREAD

**Issue by ahashem** [huseyinkozan/phonegap-bluetooth#3]
Hi huseyin,
Nice work you've made. You really saved me a lot of time.

I'm working with the ACTION_WRITE heavily and I believe there is something going wrong there that I cannot understand. Every time I connect the socketId changes to 1 (so it's connected), but when I try to write it always give me the JSON error with the decimal encoding of the entered characters.

Is this really an issue or it's just me.

Thanks

**Comment by huseyinkozan** [comment]
Hi Ahmed,
I tried read and write with i5503 and i9000, and they are working. 
Can you try example application ? 
If it does not work, can you give your configuration ? 
I mean, phones, OS versions, phonegap versions etc.

**Comment by ahashem** [comment]
Hi huseyin,
Thanks for your response. I used your recent commit and it working smoothly.
By the way, I tested the example application on Galaxy tab 10.1 (Android 3.1) and Galaxy Note (Android 4.1) and it is working.
